samsungtvws/remote.py
Will help in debugging https://github.com/home-assistant/home-assistant/pull/31537
=> Standardize logging

samsungtvws/exceptions.py, samsungtvws/remote.py
Raises a custom exception instead standard one. Always related to: https://github.com/home-assistant/home-assistant/pull/31537
=> Use custom exception

samsungtvws/remote.py
Will (hopefully) fix behaviour of https://github.com/home-assistant/home-assistant/pull/31537
=> Save token when not using token file

build/lib/samsungtvws/remote.py, samsungtvws/remote.py
* added the ability to hold a key pressed for a nubmer of seconds
* this will allow to power off completely TV's from 'The Frame' series by holding the KEY_POWER for at least 3 seconds
=> Feature - hold key

README.md, build/lib/samsungtvws/remote.py, example/example.py, requirements.txt, samsungtvws.egg-info/PKG-INFO, samsungtvws.egg-info/requires.txt, samsungtvws/exceptions.py, samsungtvws/remote.py, setup.py
* added method device_info - get device inforamtion such as device name,
model, supported features, etc.
* added dependency requests
=> Added device_info

samsungtvws/remote.py
* added move_cursor method that sends mouse move events to the TV
=> Added move_cursor

samsungtvws/helper.py
This will help debugging issues
=> Log API responses

samsungtvws/remote.py, tests/conftest.py, tests/test_remote.py
It seems that the fix provided by @chemelli74 in #26 got overriden by the work on FrameTV.
This is a tweak on the original fix to ensure that it doesn't become a breaking change.
=> Fix app_list() exception

samsungtvws/async_connection.py, samsungtvws/command.py, samsungtvws/connection.py, samsungtvws/remote.py, tests/test_remote.py
This will be used to replace the Shortcuts which are tied too closely to the sync remote.
=> Introduce a new SamsungTVCommand class

samsungtvws/async_connection.py
Sorry - one more if you haven't done the release yet...
=> Add open timeout to AsyncConnection

samsungtvws/async_connection.py, samsungtvws/connection.py
This is a simplified version of #11, but I only implemented it in async
=> Add event callback to async connection

setup.py
As per https://www.python.org/dev/peps/pep-0561/#packaging-type-information, and https://mypy.readthedocs.io/en/stable/installed_packages.html#creating-pep-561-compatible-packages
=> Publish type hints

samsungtvws/event.py, samsungtvws/exceptions.py, tests/fixtures/event_ed_installedApp_get.json, tests/fixtures/event_ms_error.json, tests/test_event.py
And add prettier hook for json formatting
=> Add event parsing

samsungtvws/async_connection.py, samsungtvws/async_remote.py, samsungtvws/connection.py
=> Add SamsungTVWSAsyncRemote

samsungtvws/connection.py, samsungtvws/remote.py
=> Add listener to sync code

tests/const.py, tests/fixtures/event_ed_apps_launch.json, tests/fixtures/event_ed_edentv_update.json, tests/fixtures/event_ms_channel_connect.json, tests/test_art.py, tests/test_async_remote.py, tests/test_event.py, tests/test_helper.py, tests/test_remote.py
and adjust all tests to use constants
=> Add connect tests

samsungtvws/remote.py, tests/test_async_remote.py
It should have been named `hold` to begin with...
=> Deprecate hold_key

samsungtvws/async_connection.py, samsungtvws/connection.py, samsungtvws/event.py
It should have been named MS_CHANNEL_CONNECT_EVENT to begin with
=> Rename "ms.channel.connect" event

samsungtvws/async_connection.py, samsungtvws/connection.py, samsungtvws/event.py, tests/const.py, tests/fixtures/event_ms_voiceapp_hide.json, tests/test_async_remote.py, tests/test_remote.py
I have also adjusted Home Assistant to ensure we don't trigger re-auth https://github.com/home-assistant/core/pull/67850
I added a warning so users think to report it and we can add them accordingly...
=> Add extra event to checks in open method

samsungtvws/async_connection.py, samsungtvws/connection.py
And simplify handling of sequences
=> Add logging to send_command

samsungtvws/async_connection.py
This will make it easier to use generics (`SamsungTVWSAsyncRemote` vs `SamsungTVEncryptedWSAsyncRemote`) in Home Assistant
=> Deprecate send_command for sending batch commands

.pre-commit-config.yaml, pyproject.toml, requirements.txt, samsungtvws/encrypted/authenticator.py
- repo: https://github.com/pre-commit/mirrors-prettier
rev: v3.1.0
- repo: https://github.com/PyCQA/isort
rev: 5.13.2
- repo: https://github.com/adrienverge/yamllint.git
rev: v1.35.1
- repo: https://github.com/pre-commit/mirrors-mypy
rev: v1.13.0
and
black>=24.10
mypy>=1.13
pre-commit>=4.0.1
pytest>=8.3.3
pytest-asyncio>=0.24
aioresponses>=0.7.7
=> Bump linters and development dependencies

samsungtvws/async_rest.py
Based on the suggestion from @chemelli74 here https://github.com/xchwarze/samsung-tv-ws-api/pull/154#issuecomment-2886645916.
=> Simplify rest request code
